import { Server as SocketIOServer, Socket } from 'socket.io';

interface SignalingMessage {
    type: 'offer' | 'answer' | 'ice-candidate';
    data: any;
    streamId: string;
}

class SignalingService {
    private io: SocketIOServer;
    private activePeers: Map<string, { socket: Socket; streamId: string }> = new Map();

    constructor(io: SocketIOServer) {
        this.io = io;
        this.setupSignalingHandlers();
    }

    private setupSignalingHandlers() {
        this.io.on('connection', (socket: Socket) => {
            console.log('Signaling client connected:', socket.id);

            // Handle SDP offer from mobile
            socket.on('stream:offer', async (data: SignalingMessage) => {
                console.log('Received offer for stream:', data.streamId);

                // Store peer connection
                this.activePeers.set(socket.id, {
                    socket,
                    streamId: data.streamId,
                });

                // Process offer and create answer
                const answer = await this.processOffer(data.data, data.streamId);

                // Send answer back to mobile
                socket.emit('stream:answer', {
                    type: 'answer',
                    data: answer,
                    streamId: data.streamId,
                });
            });

            // Handle ICE candidates
            socket.on('stream:ice-candidate', (data: SignalingMessage) => {
                console.log('Received ICE candidate for stream:', data.streamId);

                // In a real implementation, relay to peer or process
                this.processIceCandidate(data.data, data.streamId);
            });

            // Handle disconnection
            socket.on('disconnect', () => {
                console.log('Signaling client disconnected:', socket.id);

                const peer = this.activePeers.get(socket.id);
                if (peer) {
                    this.cleanupPeer(peer.streamId);
                    this.activePeers.delete(socket.id);
                }
            });
        });
    }

    private async processOffer(offer: RTCSessionDescriptionInit, streamId: string): Promise<RTCSessionDescriptionInit> {
        // In a real implementation, create RTCPeerConnection and process offer
        // For now, return a mock answer
        console.log('Processing offer for stream:', streamId);

        return {
            type: 'answer',
            sdp: 'mock-sdp-answer', // This would be generated by actual WebRTC peer
        };
    }

    private processIceCandidate(candidate: RTCIceCandidateInit, streamId: string) {
        // Process ICE candidate
        console.log('Processing ICE candidate for stream:', streamId);

        // In real implementation, add to peer connection
    }

    private cleanupPeer(streamId: string) {
        console.log('Cleaning up peer for stream:', streamId);

        // Clean up resources, close connections, etc.
    }

    // Notify mobile client of connection status
    notifyConnectionStatus(streamId: string, status: 'connected' | 'disconnected' | 'failed') {
        this.activePeers.forEach((peer) => {
            if (peer.streamId === streamId) {
                peer.socket.emit('stream:connection-status', { streamId, status });
            }
        });
    }

    // Get active stream count
    getActiveStreamCount(): number {
        return this.activePeers.size;
    }
}

export default SignalingService;
